### ISSUE TITLE
Fix auto-tick issue when no subfields selected

### ISSUE THREAD

**Issue by fatalbert3390** [OneGraph/graphiql-explorer#58]
It would be nice in the case where when no subfields are selected under certain headings, running a query didn't automatically check every single box available for that heading. For example:

I drill into `policyDetail > settings > items`, but I don't tick any boxes under `items`. I would expect to get the same error when you don't expand any of the subfields under `settings`:

<img width="743" alt="2020-07-30 20_40_08" src="https://user-images.githubusercontent.com/25424055/88987743-e06e0e80-d2a4-11ea-86ab-e87853b0e491.png">

However, you end up with this happening: 

<img width="594" alt="2020-07-30 20_32_31" src="https://user-images.githubusercontent.com/25424055/88987408-d7307200-d2a3-11ea-9ce9-098fa850b384.png">

All of the boxes under the `items` subfield are automatically checked when you run the policy, forcing you to have to go back and uncheck all of the subfields that were auto-selected. 

Is there a way to make the behavior the same for fields with checkboxes vs. those without?

**Comment by dwwoelfel** [comment]
It should only add the first two leaf fields by default. You can control the behavior by providing the `getDefaultFieldNames` prop to the Explorer. 

There is a default value defined in `Explorer.js`.

**Comment by dwwoelfel** [comment]
Thinking about this a bit more--the behavior you're seeing is when you run the query and it's caused by graphiql itself, not the Explorer. You should provide the custom `getDefaultFieldNames` prop to the `GraphiQL` component. You can use the default one we defined for the explorer: https://github.com/OneGraph/graphiql-explorer/blob/00881cc5b0f17a78d5ef8c5f64e0a85cbb6d5ec8/src/Explorer.js#L218
